### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by hyqneuron** [AI-ON/ai-on.org#7]
1. where does the community hang out? gitter?
2. github doesn't look right. Maybe wiki would be better?
3. we need a proper discussion platform, slack?

**Comment by 0bserver07** [comment]
Hey @hyqneuron one thing that was suggested here: #5 is having each repo as a starting point for collecting relevant work, sources and such.

I believe each project do have a google-group for now as well.

Also, It could depend on each group's preference perhaps for different discussion different platforms can help. 

There might be a slack channel coming (I believe), but from experience (Gitter) has been a more open-friendly approach, while Slack could be slower for onboarding, though it has been used for more focused conversations.

edit: @odellus, yup.
Perhaps @fchollet , can help us creating the gitter chat (that is related to the org, since he is owner of the org/setting).

A good case study is the Keras / OpenAI chat, that is open and can have back and forth conversation.

Meanwhile as I mentioned earlier, for specific projects (in my experience, it comes down to the group)

I do open research and we use tools like:
1. Google Hangout / Groups
2. Skype Groups
3. Gitter
4. Email threads.
5. Meeting ?
6. lastly within Slack sometimes.

**Comment by odellus** [comment]
+1 for gitter over slack.

**Comment by fchollet** [comment]
I attempted to create a AION Gitter but ran into issues (bugs in the Gitter web API -- seems to be a frequent occurrence). Please feel free to create one yourself, if you can!

**Comment by fchollet** [comment]
Additionally, I would advise against using Skype. We should stay in touch via platforms that have free unlimited searchable archives of communications.

**Comment by 0bserver07** [comment]
Sounds good!
Here is the [Gitter](https://gitter.im/ai-open-network/Lobby) link.

I will add it to the Main Repo + Site as well.

Hopefully this can be used for topic discussions and as an _open_ communication style 😄 

edit: Thanks @cicobalico , I'm adding it to the main repo as well in a bit :).

**Comment by cicobalico** [comment]
Gitter link seems to be broken

**Comment by alexisylchan** [comment]
@cicobalico https://gitter.im/ai-open-network/Lobby seems to work for me. Maybe Gitter was down

**Comment by hyqneuron** [comment]
try this link
https://gitter.im/ai-open-network/Lobby

ᐧ
